Component
tonkatsu-ansin/Glendar pull request #41
Opened 2017-01-17 02:24 UTC by AC3ROZ

だれかCSS当ててくれ頼む

2017-01-17 04:07 UTC, potato4d commented
取り敢えずざっと見た後引き継ぎます

2017-01-17 04:07 UTC, AC3ROZ commented
愛してる

2017-01-17 04:14 UTC, potato4d requested changes
取り敢えずざっと
スマホからだから細かいのあったら後で書くかも

2017-01-17 04:14 UTC, potato4d commented on .tern-port
> +52413
これ消しといて

2017-01-17 04:14 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +        <div class="form.position">
CSSのclassとv-modelぐちゃぐちゃやんけ

2017-01-17 04:14 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +        <button type="submit" class="dialogButton" value="OK" v-on:click="onClickOKButton">OK</button>
CSSのclassとv-modelぐちゃぐちゃやんけ

2017-01-17 04:14 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +<template lang="html">
どっちゃでもええけどlangいらんで

2017-01-17 04:14 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +      let btns = document.querySelectorAll(".dialogButton");
これ普通にgenerator function無理に使わずにかけるぞ

2017-01-17 04:14 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +        <button type="submit" class="dialogButton" value="Cancel" v-on:click="dismiss">Cancel</button>
clickで受けるイベントだからtypeはsubmitで良い

2017-01-18 01:33 UTC, AC3ROZ commented on src/components/Interface/ComponentaddDialog.vue
> +        <button type="submit" class="dialogButton" value="Cancel" v-on:click="dismiss">Cancel</button>
input使えって話？

2017-01-18 01:39 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +        <button type="submit" class="dialogButton" value="Cancel" v-on:click="dismiss">Cancel</button>
@AC3ROZ 
まって日本語死んでた。

```
<button type="submit">cancel</button>
```

だとfromのsubmitイベントが発火するけど、

```
<button type="button">test</button>
```

だとクリックしてもformのsubmitイベントが発火しないから、キャンセルボタンの方はtypeをbuttonにしたほうが良さそうって話し

2017-01-18 01:40 UTC, AC3ROZ commented on src/components/Interface/ComponentaddDialog.vue
> +        <button type="submit" class="dialogButton" value="Cancel" v-on:click="dismiss">Cancel</button>
理解をした

2017-01-18 01:41 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +        <button type="submit" class="dialogButton" value="Cancel" v-on:click="dismiss">Cancel</button>
generatorなくてイケるかもってコメントしたのは$("button")を捜査してそうだったからセレクタ変えたらイケるんじゃねみたいな感じでコメントしてたけどまだちゃんとコード読んでないからその辺はThroughで頼む

2017-01-18 01:42 UTC, AC3ROZ commented on src/components/Interface/ComponentaddDialog.vue
> +      let btns = document.querySelectorAll(".dialogButton");
毎回querySelectorAll走らないから精神衛生上よくない？

2017-01-18 05:23 UTC, potato4d commented on src/components/Interface/ComponentaddDialog.vue
> +      let btns = document.querySelectorAll(".dialogButton");
ごめん普通に仕事だった
document.qsaじゃなくてthis.$el.qsaだとスコープも狭まるし特に問題ないんじゃないかな

2017-01-18 13:24 UTC, potato4d approved these changes

2017-01-18 13:24 UTC, merged